# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BYndSRY0Tk6uaVYmIJGufyKOTfKQDiWC
"""

import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin

def crawl_website(url):
    try:
        response = requests.get(url, timeout=10)
        response.raise_for_status()
    except:
        return None

    soup = BeautifulSoup(response.text, "html.parser")

    # Remove unwanted tags
    for tag in soup(["header", "footer", "nav", "script", "style", "aside"]):
        tag.decompose()

    text = soup.get_text(separator=" ")
    return text

!pip install --upgrade langchain langchain-community langchain-text-splitters

!pip install -U langchain langchain-community langchain-text-splitters
from langchain_text_splitters import RecursiveCharacterTextSplitter

from langchain_text_splitters import RecursiveCharacterTextSplitter

def process_text(text):
    splitter = RecursiveCharacterTextSplitter(
        chunk_size=500,
        chunk_overlap=50
    )
    chunks = splitter.split_text(text)
    return chunks

!pip install faiss-cpu

from sentence_transformers import SentenceTransformer
import faiss
import os
import pickle

model = SentenceTransformer("all-MiniLM-L6-v2")

def create_embeddings(chunks):
    vectors = model.encode(chunks)
    return vectors

def save_embeddings(vectors, chunks):
    os.makedirs("data", exist_ok=True)

    index = faiss.IndexFlatL2(vectors.shape[1])
    index.add(vectors)

    faiss.write_index(index, "data/index.faiss")

    with open("data/chunks.pkl", "wb") as f:
        pickle.dump(chunks, f)

def load_embeddings():
    index = faiss.read_index("data/index.faiss")
    with open("data/chunks.pkl", "rb") as f:
        chunks = pickle.load(f)
    return index, chunks

import pickle

def load_embeddings(file_path="embeddings.pkl"):
    with open(file_path, "rb") as f:
        return pickle.load(f)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile embeddings.py
# import pickle
# 
# def load_embeddings(file_path="embeddings.pkl"):
#     with open(file_path, "rb") as f:
#         return pickle.load(f)
#

from embeddings import load_embeddings
print("Embeddings module loaded successfully!")

import sys
sys.path.append('/content')

from embeddings import load_embeddings

from sentence_transformers import SentenceTransformer
import numpy as np
from embeddings import load_embeddings

model = SentenceTransformer("all-MiniLM-L6-v2")

def answer_question(question):
    try:
        index, chunks = load_embeddings()
    except:
        return "Please index a website first."

    q_vector = model.encode([question])
    D, I = index.search(q_vector, k=3)

    context = " ".join([chunks[i] for i in I[0]])

    if len(context.strip()) == 0:
        return "The answer is not available on the provided website."

    return context[:500]  # simple answer (LLM can be added later)

!pip install streamlit

!pip install streamlit pyngrok

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# 
# st.title("Hello Streamlit in Colab!")
# st.write("Streamlit is working!")
#

from pyngrok import ngrok
ngrok.set_auth_token("2yShxu6XhJhYAiXxl1XO6VVPKgL_72tfC1wDAqGhDDWj7J8PY")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile crawler.py
# import requests
# from bs4 import BeautifulSoup
# 
# def crawl_website(url):
#     """
#     Takes a website URL and returns all text content from the page.
#     """
#     response = requests.get(url)
#     soup = BeautifulSoup(response.text, "html.parser")
#     return soup.get_text()
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile processor.py
# from langchain_text_splitters import RecursiveCharacterTextSplitter
# 
# def process_text(text):
#     """
#     Splits text into chunks for embeddings or search.
#     """
#     splitter = RecursiveCharacterTextSplitter(
#         chunk_size=500,
#         chunk_overlap=50
#     )
#     return splitter.split_text(text)
#

from processor import process_text

text = "This is a test text to split into chunks."
chunks = process_text(text)
print(chunks)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile embeddings.py
# from sentence_transformers import SentenceTransformer
# import pickle
# 
# model = SentenceTransformer("all-MiniLM-L6-v2")
# 
# def create_embeddings(chunks):
#     return model.encode(chunks)
# 
# def save_embeddings(embeddings, file_path="embeddings.pkl"):
#     with open(file_path, "wb") as f:
#         pickle.dump(embeddings, f)
# 
# def load_embeddings(file_path="embeddings.pkl"):
#     with open(file_path, "rb") as f:
#         return pickle.load(f)
#

# Remove cached module
import sys
if 'embeddings' in sys.modules:
    del sys.modules['embeddings']

from embeddings import create_embeddings, save_embeddings, load_embeddings

# Test
chunks = ["Hello world", "This is a test"]
embs = create_embeddings(chunks)
print("Embeddings shape:", embs.shape)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile chatbot.py
# import numpy as np
# 
# def answer_question(question, chunks, embeddings, model):
#     """
#     Simple RAG-style retrieval using cosine similarity.
#     Returns the chunk most similar to the question.
#     """
#     # Get embedding for the question
#     q_emb = model.encode([question])
# 
#     # Compute cosine similarity with existing embeddings
#     scores = np.dot(embeddings, q_emb.T).flatten()
# 
#     # Get the index of the best matching chunk
#     best_idx = np.argmax(scores)
# 
#     return chunks[best_idx]
#

from chatbot import answer_question

print("Chatbot module imported successfully!")

import streamlit as st
from crawler import crawl_website
from processor import process_text
from embeddings import create_embeddings, save_embeddings
from chatbot import answer_question

st.title("🌐 Website AI Chatbot")

import streamlit as st
from crawler import crawl_website
from processor import process_text
from embeddings import create_embeddings, save_embeddings
from chatbot import answer_question

st.title("🌐 Website AI Chatbot")

url = st.text_input("Enter Website URL:")

if st.button("Index Website"):
    text = crawl_website(url)

    if text is None:
        st.error("Invalid or unreachable URL.")
    else:
        chunks = process_text(text)
        vectors = create_embeddings(chunks)
        save_embeddings(vectors, chunks)
        st.success("Website Indexed Successfully!")

question = st.text_input("Ask a question:")

if st.button("Ask"):
    answer = answer_question(question)
    st.write("🤖 Answer:", answer)

